### ISSUE TITLE
Multiple energy meters on single ESP8266?

### ISSUE THREAD

**Issue by balk77** [jorgeassuncao/WEM#1]
Hi, does MAID-EM support connecting multiple energy meters simultaneously to a single ESP8266?

**Comment by jorgeassuncao** [comment]
Not at the moment but it could support it with a total code change. And i'm not planning that at the moment because of time constrains.

**Comment by balk77** [comment]
Okay, clear answer. Thanks for the effort you've put into this project! I'll stick to multiple esp boards.
