### ISSUE TITLE
solicitando apoyo para grafana y influxdb

### ISSUE THREAD

**Issue by spereg53** [jorgeassuncao/WEM#2]
hola:soy de mexico y solicito una ayuda para terminar lo del  proyecto de medicion de energia por los impulsos ,ya tengo lo del node-red y veo los kwh,watss y kwhacunulados ya cree en influxdb una base de datos se llama kwhacu y veo los datos en modo texto ,no puedo verlos en grafana,gracias
name: pulse
time                value
----                -----
1529598708828884881  1.23
1529598746556454091  1.24
1529598867021636275  1.24
1529598987495703960  1.24
1529599065804360625  1.24
1529599107963470580  1.24
1529599228435401891  1.25
1529599348899341036  1.25
1529599469373568823  1.25
1529599589845730656  1.26
1529599710294654877  1.26
1529599830786038624  1.26
1529599951247048395  1.26
1529600071720806197  1.27
1529600192162917808  1.27
,tengo configurado en grafan esa base de datos y solo que no s ven los datos,me puede apoyar??

**Comment by jorgeassuncao** [comment]
How are you sending the data to InfluxDB? Are you using Home Assistant?

**Comment by spereg53** [comment]
no raspbian stretch con node-red,influx server y grafana instalados,me
funciona con el dashboard propio de node—red pero con grafana no lee nada y
veo en modo texto los datos dentro del acl de influx

El 24 jun. 2018 7:14 PM, "Jorge Assunção" <notifications@github.com>
escribió:

How are you sending the data to InfluxDB? Are you using Home Assistant?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jorgeassuncao/MAID-EM/issues/2#issuecomment-399800501>,
or mute the thread

**Comment by jorgeassuncao** [comment]
Is the connection between InfluxDB and Grafana correctly configured?

**Comment by spereg53** [comment]
i have made a conexion with timestamp from node-red ,influx and grafana and
it work!!!!

ING.SERGIO M.PEREZ GORDILLO
CALLE DE CHAMULA #21
COL.LA LOMITA;C.P.29060
TUXTLA GTZ.CHIAPAS,MEXICO
TEL:019612640373 y
019611214526
CELULAR:9612015537
Email:spereg53@gmail.com
Email:spereg_53@hotmail.com

**Comment by jorgeassuncao** [comment]
Great. Glad you've made it!
